version: "3.7"
services:

  grpc_service:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["server.py"]
    env_file:
      - .env
    networks:
      image_service_mesh:
        aliases:
          - grpc_service
    expose:
      - "22222"

  client:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["client.py"]
    networks:
      image_service_mesh:
        aliases:
          - client
    ports:
      - "5000:5000"

networks:
  image_service_mesh: {}
